### ISSUE TITLE
Sorry to use this to communicate

### ISSUE THREAD

**Issue by SoLongSidekick** [Herushan/Pinecil_LED_Ring#2]
I don't have a twitter or discord, I hope this is ok.

I'm just wondering why you didn't go full surface mount for the Pinecil LED ring? I was gonna modify the PCB to do it myself but figured there might have been a reason and that I should ask. When I saw that there is a space for a single surface mount LED on the board I got really confused as to why there was one but not all. 

Secondarily any chance you have any PCBs still laying around? I can make them myself with pre-sensitized copper clad and either my laser cutter or SLA 3D printer but would rather have an OSHPark one if there's still one laying around. I'd also be interested in buying a hall effect chip or thumbscrew if you have any extras as well.

Thanks for all the work, freaking awesome mod!

**Comment by Herushan** [comment]
You ask a good question that I probably need to verify that the information why is well documented on why I prefer the through hole LEDs on the side instead of SMD. First I want to point out that the through hole pads are done in a way that SMD LEDs can be mounted to them without issue as I did that when prototyping and testing what is best. The testing showed that SMD LEDs did not focus the light as well to the soldering area as the through hole options and is not as effective in the lights purpose. The one SMD on the bottom gives the right amount of flood light and keeps the shadowing down caused by the tip. I could not do a through hole on the bottom in keeping the minimalist design. Feel free to use the same size SMD as the bottom for the sides if you would like. 

I do have sets available and do not charge a lot as I want to see people enjoy the mod. If you just want the PCB I can do that as well. I have a KoFi page and am on LinkedIn and Reddit as well for DMs to work details.
